version: '3.7'
name: mdevoldere-php-dwwm2305
services: 
  db:
    image: mariadb:11
    container_name: mdevoldere-db-mysql-2503
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./backups:/backups
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user 
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: root

  web:
    image: "php:8.4-apache"
    container_name: mdevoldere-lamp-apache2-2503
    restart: always
    depends_on: ['db']
    ports: ['80:80']
    links: ['db:db']
    volumes:
      - './public:/var/www/html'
      - './src:/var/www/src'
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DATABASE: test
      MYSQL_USER: user 
      MYSQL_PASSWORD: user

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: mdevoldere-lamp-phpmyadmin-2503
    restart: always
    depends_on: ['db']
    ports: ['1200:80']
    links: ['db:db']
    environment:
      - MYSQL_DB_HOST=db
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=user


volumes:
  db_data: {}
